Repository tensorflow/examples, pull requests merged in 2020-07, with the labels that each got.

#227 image scale operator should works for different pixel formats, not limited to BGRA
  lite/examples/object_detection/ios/ObjectDetection/Extensions/CVPixelBufferExtension.swift
Labels: cla: yes, ready to pull

#229 multiclass text classification solution
  community/en/text_classification_solution.ipynb
Labels: cla: yes

#233 Fix bug in Android speech_commands average score calculation
  lite/examples/speech_commands/android/app/src/main/java/org/tensorflow/lite/examples/speech/RecognizeCommands.java
Labels: cla: yes, ready to pull, size:XS

#234 Fixed typos in position_encoding.ipynb
  community/en/position_encoding.ipynb
Labels: cla: yes, kokoro:force-run, ready to pull, size:XS
