Repository tensorflow/examples, pull requests merged in 2021-03, with the labels that each got.

#290 Remove not used variable in PoseNet
  lite/examples/posenet/ios/PoseNet/ModelDataHandler/ModelDataHandler.swift
Labels: cla: yes, kokoro:force-run, ready to pull, size:S

#295 Update tflite_c02_transfer_learning.ipynb
  courses/udacity_intro_to_tensorflow_lite/tflite_c02_transfer_learning.ipynb
Labels: cla: yes, ready to pull, size:XS

#297 Copy a3c blogpost from tensorflow/models
  community/en/a3c_blogpost/README.md
  community/en/a3c_blogpost/a3c_cartpole.py
Labels: cla: yes, ready to pull, size:L
